export const OBJECTIVES: Record<string, string[]> = {
  en: [
    'Lionel Messi',
    'Python (programming language)',
    'SpaceX',
    'Elon Musk',
    'Taylor Swift',
    'Star Wars',
    'Minecraft',
    'Netflix',
    'Bitcoin',
    'Quantum mechanics',
    'Ancient Egypt',
    'Industrial Revolution',
    'Artificial intelligence',
    'World War II',
    'The Beatles',
    'Amazon (company)',
    'Google',
    'NASA',
    'Hollywood',
    'Olympic Games',
  ],
  es: [
    'Lionel Messi',
    'Boca Juniors',
    'Python (lenguaje de programación)',
    'SpaceX',
    'Elon Musk',
    'Taylor Swift',
    'Star Wars',
    'Minecraft',
    'Netflix',
    'Bitcoin',
    'Mecánica cuántica',
    'Antiguo Egipto',
    'Revolución Industrial',
    'Inteligencia artificial',
    'Segunda Guerra Mundial',
    'The Beatles',
    'Amazon',
    'Google',
    'NASA',
    'Hollywood',
    'Juegos Olímpicos',
  ],
};
