export const STARTERS: Record<string, string[]> = {
  en: [
    'Earth',
    'Human',
    'Internet',
    'Science',
    'History',
    'Philosophy',
    'Biology',
    'Physics',
    'Chemistry',
    'Mathematics',
    'Literature',
    'Art',
    'Music',
    'Cinema',
    'Geography',
    'Evolution',
    'Industrial Revolution',
    'French Revolution',
    'Ancient Greece',
    'Ancient Rome',
    'Renaissance',
    'Middle Ages',
    'World War I',
    'World War II',
    'Cold War',
    'Space Race',
    'Apollo 11',
    'Solar System',
    'Milky Way',
    'Galaxy',
    'Universe',
    'Big Bang',
    'Evolutionary biology',
    'Genetics',
    'DNA',
    'Brain',
    'Neuroscience',
    'Psychology',
    'Sociology',
    'Economics',
    'Politics',
    'Democracy',
    'Capitalism',
    'Socialism',
    'Globalization',
    'Climate change',
    'Renewable energy',
    'Computers',
    'Programming language',
    'Algorithm',
  ],
  es: [
    'Tierra',
    'Humano',
    'Internet',
    'Ciencia',
    'Historia',
    'Filosofía',
    'Biología',
    'Física',
    'Química',
    'Matemáticas',
    'Literatura',
    'Arte',
    'Música',
    'Cine',
    'Geografía',
    'Evolución',
    'Revolución Industrial',
    'Revolución francesa',
    'Antigua Grecia',
    'Antigua Roma',
    'Renacimiento',
    'Edad Media',
    'Primera Guerra Mundial',
    'Segunda Guerra Mundial',
    'Guerra Fría',
    'Carrera espacial',
    'Apolo 11',
    'Sistema solar',
    'Vía Láctea',
    'Galaxia',
    'Universo',
    'Big Bang',
    'Biología evolutiva',
    'Genética',
    'ADN',
    'Cerebro',
    'Neurociencia',
    'Psicología',
    'Sociología',
    'Economía',
    'Política',
    'Democracia',
    'Capitalismo',
    'Socialismo',
    'Globalización',
    'Cambio climático',
    'Energía renovable',
    'Computadora',
    'Lenguaje de programación',
    'Algoritmo',
  ],
};
